### ISSUE TITLE
Issue with alias

### ISSUE THREAD

**Issue by Hiteshm01** [brianc/node-sql#211] opened 2015-02-20 10:28 UTC
While using alias I got a query like below one, 

```SELECT `user`.`name`, `subposts`.`content` FROM `user` AS `user_test` INNER JOIN (SELECT `postsss`.`content`, MAX(`postsss`.`userId`) AS `userId_max` FROM `post` AS `postsss`) subposts ON (`user`.`id` = ?)```

Shouldn't user.name be replaced with user_test.name?

**Comment by danrzeppa** [comment] 2015-02-20 14:42
Please provide source code with a simple a sample that reproduces the issue.

**Comment by Hiteshm01** [comment] 2015-02-20 14:47
Uploaded my test file (test/dialects/aggregate-tests.js) to https://gist.github.com/Hiteshm01/a0a20ac87642d0bbdc56

**Comment by danrzeppa** [comment] 2015-02-20 15:40
When I run that query (not in the test harness because I'm running on Windows right now), I get this result:

```sql
SELECT `user`.`name`, `subposts`.`content`
FROM `user` AS `aasd` 
  INNER JOIN (SELECT `post`.`content`, MAX(`post`.`userId`) AS `userId_max` FROM `post`) subposts ON (`user`.`id` = ?)
```

I'm running the latest version from npm. What are you seeing or not seeing?

**Comment by Hiteshm01** [comment] 2015-02-20 16:02
@danrzeppa : correct, as you can see, user table is aliased as `aasd` (sorry for such senseless name), shoudn't select statement be 
```
SELECT `aasd`.`name`, `subposts`.`content` '
```
instead of 
```
SELECT `user`.`name`, `subposts`.`content`
```

**Comment by danrzeppa** [comment] 2015-02-20 16:21
I see what you're saying. And yes, I agree with you. There does seem to be an issue there. For anyone else reading this the sample can really be broken down to
```javascript
var query=user.select(user.name).from(user.as("a"))
```
Currently generates:
```sql
SELECT `user`.`name` FROM `user` AS `a`
```
But should generate:
```sql
SELECT `a`.`name` FROM `user` AS `a`
```

**Comment by Hiteshm01** [comment] 2015-02-20 17:46
Figured out an alternative as 
```
customer.select(customer.as('temp_name').name).from(customer.as("temp_name")),
```
generated 
```
SELECT `temp_name`.`name` FROM `customer` AS `temp_name`
```

But I still feel it should be handled in example suggested by @danrzeppa

**Comment by spion** [comment] 2015-02-20 18:25
I disagree. When doing self-joins, how will it know which name to use?

You can just put the alias in a var:

```js
var mentor = user.as('mentor')
user.from(user.join(mentor).on(user.mentor_id.equals(mentor.id))
  .where(...)
```

```js
var temp_name = customer.as('temp_name')
customer.select(temp_name.name).from(temp_name);
```

**Comment by Hiteshm01** [comment] 2015-02-20 18:31
Agreed. Missed this case altogether and spent last hour just to place a fix for this. My bad.

**Comment by danrzeppa** [comment] 2015-02-20 18:52
@spion disagree with what exactly?

**Comment by spion** [comment] 2015-02-20 19:01
@danrzeppa oh sorry, forgot to explain it. I disagree that the alias should change how the original table behaves

```js
var query=user.select(user.name).from(user.as("a"))
```

This is now how it should work, mostly because of the self-join issue above, but also, it shouldn't be too much trouble to just put the alias in a var; besides its less prone to surprises.

Infact I'm not even sure its possible without major changes (in the example above `user.as` will be executed after `user.name`)

**Comment by danrzeppa** [comment] 2015-02-20 20:19
My concern is that
```javascript
var query=user.select(user.name).from(user.as("a"))
```
Generates invalid SQL:
```sql
SELECT `user`.`name` FROM `user` AS `a`
```
If this did generate working sql:
```sql
SELECT `a`.`name` FROM `user` AS `a`
```
It wouldn't break any self joins, since you've already aliased the other table as well.

Regarding whether it's actually possible to implement this, that I don't know. I haven't dug into the code surrounding aliases enough to know yet.

**Comment by spion** [comment] 2015-02-21 00:57
I don't understand. There is no other table, its the same table instance. How will

```js
user.select(user.name).from(user.as('user').join(user.as('mentor')).where(user.id.equals(user.mentor_id)))
```

know which user is which there? :D 

However yes, there are many other ways to generate similarly invalid SQL from node-sql, e.g.

```js
var query = user.select(user.name).from(post)
```

So it might be worthwhile to check whether parameters passed to select match the set of things that are listed in `.from` and throw an error if they're not present when generating the query (instead of assuming an alias)?

**Comment by danrzeppa** [comment] 2015-02-22 10:13
@spion I agree with you. I'm not sure it could even be implemented correctly the way I'm suggesting. I see how there can be some confusion, if you come at the problem how you would write it in SQL. The 
```
var query=user.select(user.name).from(user.as("a"))
```
syntax maps very closely to how it would be written in SQL
```
SELECT a.name FROM user as a
```
Which even I initially *thought* would work.

In conclusion, I don't think there is anything that needs to be done here. In order to alias a table it needs to be done ahead of where the table is being used. I'd recommend we close this issue unless anyone else disagrees.

**Closed** 2015-03-26 10:33 UTC
